# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\RF_TOOL\RF_TOOL-master\ui\mw.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(933, 962)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 1881, 901))
        self.tabWidget.setObjectName("tabWidget")
        self.tabFFT = QtWidgets.QWidget()
        self.tabFFT.setObjectName("tabFFT")
        self.specWid = fftWid(self.tabFFT)
        self.specWid.setGeometry(QtCore.QRect(60, 120, 201, 361))
        self.specWid.setObjectName("specWid")
        self.controlSpecGroupBox = QtWidgets.QGroupBox(self.tabFFT)
        self.controlSpecGroupBox.setGeometry(QtCore.QRect(550, 80, 210, 611))
        self.controlSpecGroupBox.setMinimumSize(QtCore.QSize(210, 0))
        self.controlSpecGroupBox.setMaximumSize(QtCore.QSize(210, 16777215))
        self.controlSpecGroupBox.setObjectName("controlSpecGroupBox")
        self.layoutWidget_11 = QtWidgets.QWidget(self.controlSpecGroupBox)
        self.layoutWidget_11.setGeometry(QtCore.QRect(10, 20, 191, 551))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget_11)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_12.addWidget(self.label_9, 4, 0, 1, 1)
        self.cntPushButton = QtWidgets.QPushButton(self.layoutWidget_11)
        self.cntPushButton.setObjectName("cntPushButton")
        self.gridLayout_12.addWidget(self.cntPushButton, 4, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_33.setObjectName("label_33")
        self.gridLayout_12.addWidget(self.label_33, 2, 0, 1, 1)
        self.specWinComboBox = QtWidgets.QComboBox(self.layoutWidget_11)
        self.specWinComboBox.setObjectName("specWinComboBox")
        self.specWinComboBox.addItem("")
        self.specWinComboBox.addItem("")
        self.specWinComboBox.addItem("")
        self.specWinComboBox.addItem("")
        self.specWinComboBox.addItem("")
        self.gridLayout_12.addWidget(self.specWinComboBox, 2, 1, 1, 2)
        self.complSpecCheckBox = QtWidgets.QCheckBox(self.layoutWidget_11)
        self.complSpecCheckBox.setChecked(True)
        self.complSpecCheckBox.setObjectName("complSpecCheckBox")
        self.gridLayout_12.addWidget(self.complSpecCheckBox, 0, 0, 1, 3)
        self.clearSpecPushButton = QtWidgets.QPushButton(self.layoutWidget_11)
        self.clearSpecPushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.clearSpecPushButton.setObjectName("clearSpecPushButton")
        self.gridLayout_12.addWidget(self.clearSpecPushButton, 10, 0, 1, 3)
        self.info0PushButton = QtWidgets.QPushButton(self.layoutWidget_11)
        self.info0PushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.info0PushButton.setObjectName("info0PushButton")
        self.gridLayout_12.addWidget(self.info0PushButton, 9, 0, 1, 3)
        self.markerPeakPushButton = QtWidgets.QPushButton(self.layoutWidget_11)
        self.markerPeakPushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.markerPeakPushButton.setObjectName("markerPeakPushButton")
        self.gridLayout_12.addWidget(self.markerPeakPushButton, 11, 0, 1, 3)
        self.RD_cntSpinBox = QtWidgets.QSpinBox(self.layoutWidget_11)
        self.RD_cntSpinBox.setMinimum(10)
        self.RD_cntSpinBox.setMaximum(999999999)
        self.RD_cntSpinBox.setSingleStep(100)
        self.RD_cntSpinBox.setProperty("value", 10000)
        self.RD_cntSpinBox.setDisplayIntegerBase(10)
        self.RD_cntSpinBox.setObjectName("RD_cntSpinBox")
        self.gridLayout_12.addWidget(self.RD_cntSpinBox, 4, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_12.addLayout(self.horizontalLayout_6, 12, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget_11)
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 7, 0, 1, 2)
        self.speclegTableWidget = QtWidgets.QTableWidget(self.layoutWidget_11)
        self.speclegTableWidget.setObjectName("speclegTableWidget")
        self.speclegTableWidget.setColumnCount(0)
        self.speclegTableWidget.setRowCount(0)
        self.gridLayout_12.addWidget(self.speclegTableWidget, 8, 0, 1, 3)
        self.midSpinBox = QtWidgets.QSpinBox(self.layoutWidget_11)
        self.midSpinBox.setMinimum(1)
        self.midSpinBox.setSingleStep(5)
        self.midSpinBox.setObjectName("midSpinBox")
        self.gridLayout_12.addWidget(self.midSpinBox, 7, 2, 1, 1)
        self.pow2ComboBox = QtWidgets.QComboBox(self.layoutWidget_11)
        self.pow2ComboBox.setObjectName("pow2ComboBox")
        self.gridLayout_12.addWidget(self.pow2ComboBox, 5, 0, 1, 2)
        self.opt_checkBox = QtWidgets.QCheckBox(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_checkBox.setFont(font)
        self.opt_checkBox.setObjectName("opt_checkBox")
        self.gridLayout_12.addWidget(self.opt_checkBox, 6, 0, 1, 3)
        self.tabWidget.addTab(self.tabFFT, "")
        self.tabOsc = QtWidgets.QWidget()
        self.tabOsc.setObjectName("tabOsc")
        self.oscWid = oscWid(self.tabOsc)
        self.oscWid.setGeometry(QtCore.QRect(80, 110, 211, 361))
        self.oscWid.setObjectName("oscWid")
        self.controlOscGroupBox = QtWidgets.QGroupBox(self.tabOsc)
        self.controlOscGroupBox.setGeometry(QtCore.QRect(330, 60, 250, 501))
        self.controlOscGroupBox.setMinimumSize(QtCore.QSize(250, 0))
        self.controlOscGroupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.controlOscGroupBox.setObjectName("controlOscGroupBox")
        self.layoutWidget = QtWidgets.QWidget(self.controlOscGroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 31, 206, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.SPEC_cntSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.SPEC_cntSpinBox.setMinimum(10)
        self.SPEC_cntSpinBox.setMaximum(999999999)
        self.SPEC_cntSpinBox.setSingleStep(100)
        self.SPEC_cntSpinBox.setProperty("value", 100)
        self.SPEC_cntSpinBox.setDisplayIntegerBase(10)
        self.SPEC_cntSpinBox.setObjectName("SPEC_cntSpinBox")
        self.gridLayout.addWidget(self.SPEC_cntSpinBox, 2, 1, 1, 1)
        self.specCntPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.specCntPushButton.setObjectName("specCntPushButton")
        self.gridLayout.addWidget(self.specCntPushButton, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.drawOscCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.drawOscCheckBox.setFont(font)
        self.drawOscCheckBox.setChecked(False)
        self.drawOscCheckBox.setObjectName("drawOscCheckBox")
        self.gridLayout.addWidget(self.drawOscCheckBox, 0, 0, 1, 3)
        self.osclegTableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.osclegTableWidget.setObjectName("osclegTableWidget")
        self.osclegTableWidget.setColumnCount(0)
        self.osclegTableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.osclegTableWidget, 3, 0, 1, 3)
        self.info1PushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.info1PushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.info1PushButton.setObjectName("info1PushButton")
        self.gridLayout.addWidget(self.info1PushButton, 4, 0, 1, 3)
        self.clearOscPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.clearOscPushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.clearOscPushButton.setObjectName("clearOscPushButton")
        self.gridLayout.addWidget(self.clearOscPushButton, 5, 0, 1, 3)
        self.tabWidget.addTab(self.tabOsc, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RF TOOL"))
        self.controlSpecGroupBox.setTitle(_translate("MainWindow", "Управление"))
        self.label_9.setText(_translate("MainWindow", "Точек:"))
        self.cntPushButton.setText(_translate("MainWindow", "OK"))
        self.label_33.setText(_translate("MainWindow", "Окно:"))
        self.specWinComboBox.setItemText(0, _translate("MainWindow", "Bartlett"))
        self.specWinComboBox.setItemText(1, _translate("MainWindow", "Нет"))
        self.specWinComboBox.setItemText(2, _translate("MainWindow", "Blackman-Harris"))
        self.specWinComboBox.setItemText(3, _translate("MainWindow", "triangular"))
        self.specWinComboBox.setItemText(4, _translate("MainWindow", "Parzen"))
        self.complSpecCheckBox.setText(_translate("MainWindow", "Комлексный спектр"))
        self.clearSpecPushButton.setText(_translate("MainWindow", "Очистить"))
        self.info0PushButton.setText(_translate("MainWindow", "Справка"))
        self.markerPeakPushButton.setText(_translate("MainWindow", "Маркер на максимум"))
        self.label.setText(_translate("MainWindow", "Усреднение"))
        self.opt_checkBox.setText(_translate("MainWindow", "Оптимизация (Auto DownSample)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFFT), _translate("MainWindow", "БПФ"))
        self.controlOscGroupBox.setTitle(_translate("MainWindow", "Управление"))
        self.specCntPushButton.setText(_translate("MainWindow", "OK"))
        self.label_10.setText(_translate("MainWindow", "Точек:"))
        self.drawOscCheckBox.setText(_translate("MainWindow", "Рисовать осциллограмму"))
        self.info1PushButton.setText(_translate("MainWindow", "Справка по управлению"))
        self.clearOscPushButton.setText(_translate("MainWindow", "Очистить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOsc), _translate("MainWindow", "Осциллограмма"))
        self.actionStart.setText(_translate("MainWindow", "Старт"))
        self.actionStop.setText(_translate("MainWindow", "Стоп"))


from fftWid import fftWid
from oscWid import oscWid
