# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\RF_TOOL\RF_TOOL-master\ui\startform.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startform(object):
    def setupUi(self, startform):
        startform.setObjectName("startform")
        startform.resize(697, 862)
        startform.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget = QtWidgets.QWidget(startform)
        self.widget.setGeometry(QtCore.QRect(11, 11, 601, 801))
        self.widget.setObjectName("widget")
        self.mainGridLayout = QtWidgets.QGridLayout(self.widget)
        self.mainGridLayout.setContentsMargins(0, 0, 0, 0)
        self.mainGridLayout.setObjectName("mainGridLayout")
        self.FOR_groupBox = QtWidgets.QGroupBox(self.widget)
        self.FOR_groupBox.setObjectName("FOR_groupBox")
        self.widget1 = QtWidgets.QWidget(self.FOR_groupBox)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 491, 281))
        self.widget1.setObjectName("widget1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.formTabWidget = QtWidgets.QTabWidget(self.widget1)
        self.formTabWidget.setObjectName("formTabWidget")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget_4.setGeometry(QtCore.QRect(40, 10, 261, 131))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.FOR_binsizeComboBox = QtWidgets.QComboBox(self.layoutWidget_4)
        self.FOR_binsizeComboBox.setObjectName("FOR_binsizeComboBox")
        self.FOR_binsizeComboBox.addItem("")
        self.FOR_binsizeComboBox.addItem("")
        self.FOR_binsizeComboBox.addItem("")
        self.FOR_binsizeComboBox.addItem("")
        self.gridLayout_2.addWidget(self.FOR_binsizeComboBox, 0, 1, 1, 1)
        self.FOR_binendianComboBox = QtWidgets.QComboBox(self.layoutWidget_4)
        self.FOR_binendianComboBox.setObjectName("FOR_binendianComboBox")
        self.FOR_binendianComboBox.addItem("")
        self.FOR_binendianComboBox.addItem("")
        self.gridLayout_2.addWidget(self.FOR_binendianComboBox, 1, 0, 1, 2)
        self.FOR_binsignComboBox = QtWidgets.QComboBox(self.layoutWidget_4)
        self.FOR_binsignComboBox.setEnabled(False)
        self.FOR_binsignComboBox.setObjectName("FOR_binsignComboBox")
        self.FOR_binsignComboBox.addItem("")
        self.FOR_binsignComboBox.addItem("")
        self.gridLayout_2.addWidget(self.FOR_binsignComboBox, 2, 0, 1, 2)
        self.FOR_bincomplexCheckBox = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.FOR_bincomplexCheckBox.setChecked(False)
        self.FOR_bincomplexCheckBox.setObjectName("FOR_bincomplexCheckBox")
        self.gridLayout_2.addWidget(self.FOR_bincomplexCheckBox, 3, 0, 1, 1)
        self.formTabWidget.addTab(self.tab_6, "")
        self.gridLayout_5.addWidget(self.formTabWidget, 1, 0, 1, 1)
        self.mainGridLayout.addWidget(self.FOR_groupBox, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 65))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 65))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(240, 0, 108, 52))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startRdPushButton = QtWidgets.QPushButton(self.widget2)
        self.startRdPushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.startRdPushButton.setMaximumSize(QtCore.QSize(50, 50))
        self.startRdPushButton.setText("")
        self.startRdPushButton.setObjectName("startRdPushButton")
        self.horizontalLayout_2.addWidget(self.startRdPushButton)
        self.startUpdPushButton = QtWidgets.QPushButton(self.widget2)
        self.startUpdPushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.startUpdPushButton.setMaximumSize(QtCore.QSize(50, 50))
        self.startUpdPushButton.setText("")
        self.startUpdPushButton.setObjectName("startUpdPushButton")
        self.horizontalLayout_2.addWidget(self.startUpdPushButton)
        self.mainGridLayout.addWidget(self.groupBox, 2, 0, 1, 1)
        self.SRC_groupBox = QtWidgets.QGroupBox(self.widget)
        self.SRC_groupBox.setObjectName("SRC_groupBox")
        self.widget3 = QtWidgets.QWidget(self.SRC_groupBox)
        self.widget3.setGeometry(QtCore.QRect(10, 10, 581, 341))
        self.widget3.setObjectName("widget3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.RD_cntSpinBox = QtWidgets.QSpinBox(self.widget3)
        self.RD_cntSpinBox.setMinimum(10)
        self.RD_cntSpinBox.setMaximum(999999999)
        self.RD_cntSpinBox.setSingleStep(100)
        self.RD_cntSpinBox.setProperty("value", 10000)
        self.RD_cntSpinBox.setDisplayIntegerBase(10)
        self.RD_cntSpinBox.setObjectName("RD_cntSpinBox")
        self.gridLayout_3.addWidget(self.RD_cntSpinBox, 0, 2, 1, 1)
        self.fsLineEdit = QtWidgets.QLineEdit(self.widget3)
        self.fsLineEdit.setObjectName("fsLineEdit")
        self.gridLayout_3.addWidget(self.fsLineEdit, 1, 2, 1, 1)
        self.fsComboBox = QtWidgets.QComboBox(self.widget3)
        self.fsComboBox.setObjectName("fsComboBox")
        self.fsComboBox.addItem("")
        self.fsComboBox.addItem("")
        self.fsComboBox.addItem("")
        self.gridLayout_3.addWidget(self.fsComboBox, 1, 3, 1, 1)
        self.pow2ComboBox = QtWidgets.QComboBox(self.widget3)
        self.pow2ComboBox.setObjectName("pow2ComboBox")
        self.gridLayout_3.addWidget(self.pow2ComboBox, 0, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.SRC_onefileRadioButton = QtWidgets.QRadioButton(self.widget3)
        self.SRC_onefileRadioButton.setChecked(True)
        self.SRC_onefileRadioButton.setObjectName("SRC_onefileRadioButton")
        self.verticalLayout.addWidget(self.SRC_onefileRadioButton)
        self.SRC_onefilechanRadioButton = QtWidgets.QRadioButton(self.widget3)
        self.SRC_onefilechanRadioButton.setEnabled(False)
        self.SRC_onefilechanRadioButton.setObjectName("SRC_onefilechanRadioButton")
        self.verticalLayout.addWidget(self.SRC_onefilechanRadioButton)
        self.SRC_filesRadioButton = QtWidgets.QRadioButton(self.widget3)
        self.SRC_filesRadioButton.setObjectName("SRC_filesRadioButton")
        self.verticalLayout.addWidget(self.SRC_filesRadioButton)
        self.SRC_sharedRadioButton = QtWidgets.QRadioButton(self.widget3)
        self.SRC_sharedRadioButton.setEnabled(False)
        self.SRC_sharedRadioButton.setObjectName("SRC_sharedRadioButton")
        self.verticalLayout.addWidget(self.SRC_sharedRadioButton)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.SRC_tabWidget = QtWidgets.QTabWidget(self.widget3)
        self.SRC_tabWidget.setObjectName("SRC_tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 39, 441, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.SRC_onefileSelectLineEdit = DropLineEdit(self.layoutWidget)
        self.SRC_onefileSelectLineEdit.setObjectName("SRC_onefileSelectLineEdit")
        self.horizontalLayout_4.addWidget(self.SRC_onefileSelectLineEdit)
        self.SRC_onefileselectFilePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.SRC_onefileselectFilePushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.SRC_onefileselectFilePushButton.setObjectName("SRC_onefileselectFilePushButton")
        self.horizontalLayout_4.addWidget(self.SRC_onefileselectFilePushButton)
        self.SRC_tabWidget.addTab(self.tab_4, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_2 = QtWidgets.QLabel(self.tab_10)
        self.label_2.setGeometry(QtCore.QRect(11, 19, 73, 23))
        self.label_2.setObjectName("label_2")
        self.SRC_onefilechanselectFilePushButton = QtWidgets.QPushButton(self.tab_10)
        self.SRC_onefilechanselectFilePushButton.setGeometry(QtCore.QRect(375, 19, 75, 23))
        self.SRC_onefilechanselectFilePushButton.setObjectName("SRC_onefilechanselectFilePushButton")
        self.SRC_onefilechanLineEdit = QtWidgets.QLineEdit(self.tab_10)
        self.SRC_onefilechanLineEdit.setGeometry(QtCore.QRect(90, 20, 279, 20))
        self.SRC_onefilechanLineEdit.setObjectName("SRC_onefilechanLineEdit")
        self.label_3 = QtWidgets.QLabel(self.tab_10)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 191, 16))
        self.label_3.setObjectName("label_3")
        self.SRC_chanlenSpinBox = QtWidgets.QSpinBox(self.tab_10)
        self.SRC_chanlenSpinBox.setGeometry(QtCore.QRect(220, 60, 42, 22))
        self.SRC_chanlenSpinBox.setObjectName("SRC_chanlenSpinBox")
        self.SRC_channComboBox = QtWidgets.QComboBox(self.tab_10)
        self.SRC_channComboBox.setGeometry(QtCore.QRect(160, 100, 69, 22))
        self.SRC_channComboBox.setObjectName("SRC_channComboBox")
        self.SRC_channComboBox.addItem("")
        self.SRC_channComboBox.addItem("")
        self.SRC_channComboBox.addItem("")
        self.SRC_channComboBox.addItem("")
        self.SRC_channComboBox.addItem("")
        self.SRC_channComboBox.addItem("")
        self.SRC_channComboBox.addItem("")
        self.SRC_channComboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.tab_10)
        self.label_6.setGeometry(QtCore.QRect(20, 100, 121, 16))
        self.label_6.setObjectName("label_6")
        self.SRC_tabWidget.addTab(self.tab_10, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.SRC_chanNcomboBox = QtWidgets.QComboBox(self.tab_5)
        self.SRC_chanNcomboBox.setGeometry(QtCore.QRect(180, 20, 69, 22))
        self.SRC_chanNcomboBox.setObjectName("SRC_chanNcomboBox")
        self.SRC_chanNcomboBox.addItem("")
        self.SRC_chanNcomboBox.addItem("")
        self.SRC_chanNcomboBox.addItem("")
        self.SRC_chanNcomboBox.addItem("")
        self.SRC_chanNcomboBox.addItem("")
        self.SRC_chanNcomboBox.addItem("")
        self.SRC_chanNcomboBox.addItem("")
        self.SRC_chanNcomboBox.addItem("")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(40, 20, 121, 16))
        self.label_7.setObjectName("label_7")
        self.SRC_chanTableWidget = DropTableWidget(self.tab_5)
        self.SRC_chanTableWidget.setGeometry(QtCore.QRect(20, 60, 431, 101))
        self.SRC_chanTableWidget.setObjectName("SRC_chanTableWidget")
        self.SRC_tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.SRC_sharedTableWidget = DropTableWidget(self.tab)
        self.SRC_sharedTableWidget.setGeometry(QtCore.QRect(20, 60, 431, 91))
        self.SRC_sharedTableWidget.setObjectName("SRC_sharedTableWidget")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(40, 20, 121, 16))
        self.label_8.setObjectName("label_8")
        self.SRC_sharedNcomboBox = QtWidgets.QComboBox(self.tab)
        self.SRC_sharedNcomboBox.setGeometry(QtCore.QRect(180, 20, 69, 22))
        self.SRC_sharedNcomboBox.setObjectName("SRC_sharedNcomboBox")
        self.SRC_sharedNcomboBox.addItem("")
        self.SRC_sharedNcomboBox.addItem("")
        self.SRC_sharedNcomboBox.addItem("")
        self.SRC_sharedNcomboBox.addItem("")
        self.SRC_sharedNcomboBox.addItem("")
        self.SRC_sharedNcomboBox.addItem("")
        self.SRC_sharedNcomboBox.addItem("")
        self.SRC_sharedNcomboBox.addItem("")
        self.SRC_tabWidget.addTab(self.tab, "")
        self.gridLayout_4.addWidget(self.SRC_tabWidget, 1, 0, 1, 2)
        self.mainGridLayout.addWidget(self.SRC_groupBox, 0, 0, 1, 1)

        self.retranslateUi(startform)
        self.formTabWidget.setCurrentIndex(0)
        self.SRC_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(startform)

    def retranslateUi(self, startform):
        _translate = QtCore.QCoreApplication.translate
        startform.setWindowTitle(_translate("startform", "RF Tool Config"))
        self.FOR_groupBox.setTitle(_translate("startform", "Формат данных"))
        self.label_5.setText(_translate("startform", "Разрядность:"))
        self.FOR_binsizeComboBox.setItemText(0, _translate("startform", "8"))
        self.FOR_binsizeComboBox.setItemText(1, _translate("startform", "16"))
        self.FOR_binsizeComboBox.setItemText(2, _translate("startform", "32"))
        self.FOR_binsizeComboBox.setItemText(3, _translate("startform", "64"))
        self.FOR_binendianComboBox.setItemText(0, _translate("startform", "little-endian"))
        self.FOR_binendianComboBox.setItemText(1, _translate("startform", "big-endian"))
        self.FOR_binsignComboBox.setItemText(0, _translate("startform", "signed"))
        self.FOR_binsignComboBox.setItemText(1, _translate("startform", "unsigned"))
        self.FOR_bincomplexCheckBox.setText(_translate("startform", "Комлексные (IQ)"))
        self.formTabWidget.setTabText(self.formTabWidget.indexOf(self.tab_6), _translate("startform", "1"))
        self.SRC_groupBox.setTitle(_translate("startform", "Источник данных"))
        self.label_9.setText(_translate("startform", "Кол-во точек"))
        self.label_10.setText(_translate("startform", "Fs:"))
        self.fsLineEdit.setText(_translate("startform", "100"))
        self.fsComboBox.setItemText(0, _translate("startform", "Hz"))
        self.fsComboBox.setItemText(1, _translate("startform", "kHz"))
        self.fsComboBox.setItemText(2, _translate("startform", "MHz"))
        self.SRC_onefileRadioButton.setText(_translate("startform", "Один файл - один канал"))
        self.SRC_onefilechanRadioButton.setText(_translate("startform", "Один файл - несколько каналов"))
        self.SRC_filesRadioButton.setText(_translate("startform", "Несколько файлов (каналов)"))
        self.SRC_sharedRadioButton.setText(_translate("startform", "Shared memory"))
        self.label.setText(_translate("startform", "Путь к файлу:"))
        self.SRC_onefileselectFilePushButton.setText(_translate("startform", "..."))
        self.SRC_tabWidget.setTabText(self.SRC_tabWidget.indexOf(self.tab_4), _translate("startform", "1"))
        self.label_2.setText(_translate("startform", "Путь к файлу:"))
        self.SRC_onefilechanselectFilePushButton.setText(_translate("startform", "..."))
        self.SRC_onefilechanLineEdit.setText(_translate("startform", "H:\\RF_TOOL\\other\\gen.pcm"))
        self.label_3.setText(_translate("startform", "Сколько  точек относится к каналу"))
        self.SRC_channComboBox.setItemText(0, _translate("startform", "1"))
        self.SRC_channComboBox.setItemText(1, _translate("startform", "2"))
        self.SRC_channComboBox.setItemText(2, _translate("startform", "3"))
        self.SRC_channComboBox.setItemText(3, _translate("startform", "4"))
        self.SRC_channComboBox.setItemText(4, _translate("startform", "5"))
        self.SRC_channComboBox.setItemText(5, _translate("startform", "6"))
        self.SRC_channComboBox.setItemText(6, _translate("startform", "7"))
        self.SRC_channComboBox.setItemText(7, _translate("startform", "8"))
        self.label_6.setText(_translate("startform", "Количество каналов"))
        self.SRC_tabWidget.setTabText(self.SRC_tabWidget.indexOf(self.tab_10), _translate("startform", "2"))
        self.SRC_chanNcomboBox.setItemText(0, _translate("startform", "1"))
        self.SRC_chanNcomboBox.setItemText(1, _translate("startform", "2"))
        self.SRC_chanNcomboBox.setItemText(2, _translate("startform", "3"))
        self.SRC_chanNcomboBox.setItemText(3, _translate("startform", "4"))
        self.SRC_chanNcomboBox.setItemText(4, _translate("startform", "5"))
        self.SRC_chanNcomboBox.setItemText(5, _translate("startform", "6"))
        self.SRC_chanNcomboBox.setItemText(6, _translate("startform", "7"))
        self.SRC_chanNcomboBox.setItemText(7, _translate("startform", "8"))
        self.label_7.setText(_translate("startform", "Количество каналов"))
        self.SRC_tabWidget.setTabText(self.SRC_tabWidget.indexOf(self.tab_5), _translate("startform", "3"))
        self.label_8.setText(_translate("startform", "Количество каналов"))
        self.SRC_sharedNcomboBox.setItemText(0, _translate("startform", "1"))
        self.SRC_sharedNcomboBox.setItemText(1, _translate("startform", "2"))
        self.SRC_sharedNcomboBox.setItemText(2, _translate("startform", "3"))
        self.SRC_sharedNcomboBox.setItemText(3, _translate("startform", "4"))
        self.SRC_sharedNcomboBox.setItemText(4, _translate("startform", "5"))
        self.SRC_sharedNcomboBox.setItemText(5, _translate("startform", "6"))
        self.SRC_sharedNcomboBox.setItemText(6, _translate("startform", "7"))
        self.SRC_sharedNcomboBox.setItemText(7, _translate("startform", "8"))
        self.SRC_tabWidget.setTabText(self.SRC_tabWidget.indexOf(self.tab), _translate("startform", "4"))


from dropLineEdit import DropLineEdit
from dropTableWidget import DropTableWidget
